return {
  -- "stevearc/conform.nvim",
  -- opts = {
  --   formatters_by_ft = {
  --     sql = { "sqlfluff" },
  --     pgsql = { "sqlfluff" },
  --   },
  --   formatters = {
  --     -- sqruff = {
  --     --   command = "sqruff",
  --     --   args = { "fix", "-" },
  --     --   stdin = true,
  --     --   cwd = function()
  --     --     return vim.fn.getcwd()
  --     --   end,
  --     -- },
  --     sqlfluff = {
  --       command = "sqlruff",
  --       args = { "format", "-" },
  --       stdin = true,
  --       cwd = function()
  --         return vim.fn.getcwd()
  --       end,
  --     },
  --   },
  -- },
}
